### ISSUE TITLE
Line "Express A14": too long

### ISSUE THREAD

**Issue by Manu1400** [SlamaFR/BULB#37] opened 2024-09-16 20:23 UTC
Not possible to display line name "Express A14"

## screenshoot(s)
<img width="315" alt="Capture d’écran 2024-09-16 à 22 22 44" src="https://github.com/user-attachments/assets/020252d0-b843-4c38-9ad3-cf87bd6b83c5">

**Comment by SlamaFR** [comment] 2024-09-16 20:47
Duplicate of #16

**Closed by SlamaFR** 2024-09-16 20:47 UTC
