### ISSUE TITLE
[bug] Export to image cut long name

### ISSUE THREAD

**Issue by Manu1400** [SlamaFR/BULB#32] opened 2024-09-16 16:38 UTC
## steps
1. Open [the editor](https://bulb.slama.io/editor/) with Google Chrome
2. Set "Aéroport Charles-de-Gaulle 2 TGV" as a stop name
3. Export the project as an picture
4. Open PNG picture (with _Aperçu_ app, on M1)

### title with an icon
![a realistic project with a long name](https://github.com/user-attachments/assets/02376d2b-c1d1-4cd1-9bd3-5675d9ddf47e)
### title without an icon
![metro_19_without_plane_icon](https://github.com/user-attachments/assets/b6765f3c-87b1-43a7-9839-2aafafff3d5b)

**Comment by SlamaFR** [comment] 2024-09-16 16:39
Duplicate of #13

**Closed by SlamaFR** 2024-09-16 16:39 UTC
